### ISSUE TITLE
Autolaunched Flows Referenced in Process Builder

### ISSUE THREAD

**Issue by CloudJedi** [pgonzaleznetwork/sfdc-happy-soup#166]
I'm not sure if this is something that isn't supported but I tried using it to search for a Flow that I know is referenced in Process Builder. It wasn't able to identify it and I got the following message.

_Unable to find any metadata items that use or reference the Flow FLOW_NAME_HERE. This either means that the Flow is not being used at all or that it is used by metadata types that are not yet supported by HappySoup.I_

**Comment by pgonzaleznetwork** [comment]
Hi @CloudJedi , thanks for reaching out! Unfortunately the support for flows is very limited due to limitations on the Salesforce API. In fact, it's so limited and I get many questions about it that I'm considering removing it altogether until I can provide better support for it. I'll think about this more...thanks!

**Comment by CloudJedi** [comment]
Okay no worries! Thanks for the quick response!

**Comment by Ameensam1** [comment]
Hi @pgonzaleznetwork,

Don't you dare touch that little support you have for flows. Kidding! actually please leave it alone. For what it does, it is still a lot helpful.

**Comment by pgonzaleznetwork** [comment]
@CloudJedi  This feature is now live! Can you please give it a try? You should be able to find references to a flow in both process builders and flows. Let me know!
