### ISSUE TITLE
Problem while querying Email Templates

### ISSUE THREAD

**Issue by TheZealousOne** [pgonzaleznetwork/sfdc-happy-soup#54]
> We are sorry, something went wrong. Please click here to log a Github issue with the following details: Server Error Error: Server Error at Object.query (/app/sfdc_apis/tooling.js:42:28) at processTicksAndRejections (internal/process/task_queues.js:93:5) at async findReferences (/app/sfdc_apis/metadata-types/EmailTemplate.js:24:25) at async seachAdditionalReferences (/app/sfdc_apis/usage.js:324:36) at async Object.getUsage (/app/sfdc_apis/usage.js:17:40) at async Object.usageJob (/app/services/jobs.js:69:20) at async Queue. (/app/services/worker.js:36:20)

**Comment by pgonzaleznetwork** [comment]
Hi @TheZealousOne ,

Does this happen consistently? i.e if you try now with the same username/org id do you receive the same error? I have a feeling this occurred during database maintenance

**Comment by TheZealousOne** [comment]
Hi Pablo,

It is still happening on every attempt with different objects selected.

I am selecting impact analysis. I believe it works if I select deployment
boundary.

‫בתאריך יום א׳, 25 באוק׳ 2020 ב-20:36 מאת ‪Pablo Gonzalez‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by pgonzaleznetwork** [comment]
Hi @TheZealousOne ,

The issue appears to be while querying the fullname of this template 00X0z0000051cEREAY

Are you able to paste this id in the browser and see the template? is it maybe in a private folder?

**Comment by pgonzaleznetwork** [comment]
@TheZealousOne You could also go to https://workbench.developerforce.com/restExplorer.php

And replace the URL in the rest explore with the following

/services/data/v48.0/tooling/query/?q=SELECT+FullName+FROM+EmailTemplate+WHERE+Id+IN+('00X0z0000051cEREAY')

Does it throw an error? You can click on "Raw Response" to see if there are errors.

**Comment by TheZealousOne** [comment]
HTTP/1.1 500 Server Error Date: Sun, 25 Oct 2020 19:39:24 GMT Content-Type:
application/json;charset=UTF-8 Transfer-Encoding: chunked Connection:
keep-alive Strict-Transport-Security: max-age=31536002; includeSubDomains
Public-Key-Pins-Report-Only:
pin-sha256="9n0izTnSRF+W4W4JTq51avSXkWhQB8duS2bxVLfzXsY=";
pin-sha256="5kJvNEMw0KjrCAu7eXY5HZdvyCS13BbA0VJG1RSP91w=";
pin-sha256="njN4rRG+22dNXAi+yb8e3UMypgzPUPHlv4+foULwl1g="; max-age=86400;
includeSubDomains; report-uri="
https://a.forcesslreports.com/hpkp-report/00D300000000aKzm"; Expect-CT:
max-age=86400, report-uri="
https://a.forcesslreports.com/Expect-CT-report/00D300000000aKzm"
X-Robots-Tag: none X-B3-TraceId: c8f484b96e1ce372 X-B3-SpanId:
c8f484b96e1ce372 X-B3-Sampled: 0 Cache-Control:
no-cache,must-revalidate,max-age=0,no-store,private Set-Cookie:
BrowserId=yPMHSBb5EeuTLOmF6T0-AQ; domain=.salesforce.com; path=/;
expires=Mon, 25-Oct-2021 19:39:23 GMT; Max-Age=31536000 Sforce-Limit-Info:
api-usage=45668/262000 Server: sfdcedge X-SFDC-Request-Id:
3eb55d37daba7279a4f7c1bb3cbe6d74
[ { "message" : "Cannot retrieve documents in a user's private folder; move
the document to a named folder", "errorCode" : "UNKNOWN_EXCEPTION"

Template folder permissions?

‫בתאריך יום א׳, 25 באוק׳ 2020 ב-21:33 מאת ‪Pablo Gonzalez‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by pgonzaleznetwork** [comment]
@TheZealousOne  that appears to be the issue as seen by the error

_Cannot retrieve documents in a user's private folder; move
the document to a named folder_

Unfortunately there's nothing much I can do to bypass this as this is just Salesforce's security mechanism. What I'll do is to better catch this error and somehow let the user know that we are unable to pull the data because of user permissions.

Can you pls confirm you are able to use the impact analysis for other things like fields, classes, etc?

**Comment by TheZealousOne** [comment]
Yes, it appears to be working for other data types.

Thank you.

‫בתאריך יום א׳, 25 באוק׳ 2020 ב-21:43 מאת ‪Pablo Gonzalez‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by pgonzaleznetwork** [comment]
@TheZealousOne the only reason this is failing is because I'm querying the template full name to see if that name is referenced in custom labels. However I don't need the name to see if the template is used in email alerts.

I'm going to redesign this feature so that even if custom labels cannot be found, you can still see references to the template on email alerts. In other words, for private templates you Will get incompleto results but this is much better than getting an error.

I'll implement this next week and Let you know. Thank you so much for the feedback!

**Comment by TheZealousOne** [comment]
Really appreciate your hard work and this amazing tool.

בתאריך יום ב׳, 26 באוק׳ 2020, 16:39, מאת Pablo Gonzalez ‏<
notifications@github.com>:

**Comment by pgonzaleznetwork** [comment]
Hi @TheZealousOne ,

This is resolved now. For email templates that reside in a user's private folder, we only try to find email alerts or apex classes that use it. The ability to see if an email template name or id is used in custom labels is reserved for public email templates.

Please note that private email alerts can't actually be used in email alerts, so using the "dependency analysis" feature on such templates will either return nothing, or return the apex classes that query the EmailTemplate object via SOQL.

Could you please give this a try and let me know if the error no longer occurs?

**Comment by pgonzaleznetwork** [comment]
@TheZealousOne Also if you are interested in learning about this tool, I invite you to have a look at how I fixed this

https://github.com/pgonzaleznetwork/sfdc-happy-soup/commit/faaf1a36dfe1f9774f1c3d000d971419c5a49b6c

Essentially I wrapped all the functionality related to custom labels in a try/catch block, so that if an error occurs, we catch it and ignore. We then continue with everything else.

This is not the most elegant solution and is really just a patch to enable you to continue to use the app. In the near future I'll figure out a more elegant way to design this.
